[project]
name = "mobilome-annotation-pipeline"
version = "2.0.2"
requires-python = ">=3.9"
dependencies = [
   "numpy==2.0.2",
   "biopython==1.85",
   "pytest==8.4.1",
   "pytest-cov==6.2.1",
]

[tool.pytest.ini_options]
pythonpath = "bin"