name: Full end-to-end pipeline test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Nextflow latest-edge
        uses: nf-core/setup-nextflow@v1
        with:
          version: "25.04.7"

      - name: Setup nf-test
        uses: nf-core/setup-nf-test@v1.3.6
        with:
          install-pdiff: true

      - name: Run Tests
        run: nf-test test --verbose --ci tests/default.nf.test
     
      - name: Move .nf-test output to non-hidden folder for artifact upload
        if: always()
        run: |
          echo "changing name of .nf-test dir"
          mv .nf-test nf-test-output

      - name: Store the nf-test results if nf-test failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: nf-test-out
          include-hidden-files: true
          path: |
            ${{ github.workspace }}/nf-test-output

